### ISSUE TITLE
Keycloak does not survive Docker Container restart

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#17]
**Describe the bug**
This bug occurs sometimes. If you stop the Docker container running Keycloak and start it again, there is a chance to run in an infinite reboot loop.

**To Reproduce**
1. Start DIVA using our `up_core.sh` script
2. Stop the Keycloak container
3. Start the Keycloak container

**Expected behavior**
Keycloak should boot without any error.

**Your environment(please complete the following information):**
 - Docker/Docker Compose version 3.9
 - DIVA version 2.2.0

**Comment by setaman** [comment]
The problem occurs only when container is restarted after Keycloak was interrupted at startup. Then the container must be removed/recreated. I just added the `--force-recreate` option to the startup script. Another solution could be to create own KC image and remove `/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json` on each container start. But it's overhelming to provide own KC image just because of this Impurity.
