### ISSUE TITLE
Unwanted User Update on looking at Entity

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#38]
**Describe the bug**
If you open a search result the user receives an update event. 

**To Reproduce**
1. Go to search page an search a resource.
2. Click on a search result.
3. You should see green update popup.
4. It is possible that you must open multiple results. The behavior is currently not clear.

**Expected behavior**
No unwanted update of the user

**Screenshots**
![image](https://user-images.githubusercontent.com/12967305/131965722-9dd80aed-3274-4305-bb6a-340d5b57a13f.png)

![image](https://user-images.githubusercontent.com/12967305/131965523-5fb1af16-029e-47d4-a693-178417d4a160.png)

**Your environment(please complete the following information):**
 - DIVA: https://github.com/FraunhoferISST/diva/commit/f7871dd46f43f36563ff0d62964b5e907692f276
 - `elasticsearch-connector` does not start from docker image and `diva-lake-adapter` has the size issue. Both will be fixed soon. One needs to start both services locally.

**Comment by setaman** [comment]
@DaTebe 

The issue is caused by the fact that the EE broadcasts the update events on general `ENTITY_UPDATE_EVENT` channel where everybody is listening for the updates. That means, each subscriber hears events from other subscribers. We should investigate this later. Current solution is to filter out events by entity `id`
